0\. Implement a function (whatever you want) and save it to a file (e.g. `function.py`). Import that file and use that function in this notebook.


In [10]:
from function import square

1\. Write the following as a list comprehension

In [11]:
# 1
ans = []
for i in range(3):
    for j in range(4):
        ans.append((i, j))
print (ans)

ans2 = [(i, j) for i in range(3) for j in range(4)]
print(ans2)

# 2
ans = map(lambda x: x*x, filter(lambda x: x%2 == 0, range(5)))
print (list(ans))

ans2 = [x**2 for x in range(5) if x%2 == 0]
print(ans2)

[(0, 0), (0, 1), (0, 2), (0, 3), (1, 0), (1, 1), (1, 2), (1, 3), (2, 0), (2, 1), (2, 2), (2, 3)]
[(0, 0), (0, 1), (0, 2), (0, 3), (1, 0), (1, 1), (1, 2), (1, 3), (2, 0), (2, 1), (2, 2), (2, 3)]
[0, 4, 16]
[0, 4, 16]


2\. Convert the following function into a pure function with no global variables or side effects

In [72]:
import copy

x = 5
def f(alist):
    for i in range(x):
         alist.append(i)
    return alist

alist = [1,2,3]
clist = copy.copy(alist)
ans = f(clist)
print (ans)
print (alist) # alist has been changed!

[1, 2, 3, 0, 1, 2, 3, 4]
[1, 2, 3]


3\. Write a `decorator` hello that makes every wrapped function print “Hello!”, i.e. something like:

```python
@hello
def square(x):
    return x*x
```



In [71]:
def hello(func):
    def wrapper(*args, **kwargs):
        print("Hello!")
        func(*args, **kwargs)
    return wrapper

@hello
def say_whee():
    print("Whee!")
    
@hello
def square(x):
    return x**2

say_whee()
print(square(2))

Hello!
Whee!
Hello!
None


4\. Write the factorial function so that it a) does and b) does not use recursion.

In [17]:
def factorial1(x):
    if x==0 or x==1:
        return 1
    else:
        return x * factorial1 (x-1)

def factorial2(x):
    f = 1
    for i in range(1,x+1):
        f *= i
    return f

print(factorial1(5))
print(factorial2(5))

120
120


5\. Use HOFs (zip in particular) to compute the weight of a circle, a disk and a sphere, assuming different radii and different densities:

```python
densities = {"Al":[0.5,1,2],"Fe":[3,4,5],"Pb": [15,20,30]}
radii = [1,2,3]
```

where the entries of the dictionary's values are the linear, superficial and volumetric densities of the materials respectively.

In particular define a list of three lambda functions using a comprehension that computes the circumference, the area and the volume for a given radius.


In [80]:
import numpy as np
densities = {"Al":[0.5,1,2],"Fe":[3,4,5],"Pb": [15,20,30]}
radii = [1,2,3]
weight = {"Al":np.zeros((3,3)),"Fe":np.zeros((3,3)),"Pb":np.zeros((3,3))}

lambdaf = [(lambda r: np.pi * r**2), (lambda r: np.pi * r**2), (lambda r: 4 * np.pi * r**3 / 3)]

for i,x,y,z in zip(range(3),densities["Al"],densities["Fe"],densities["Pb"]):
    for j in range(len(radii)):
        weight["Al"][i][j] = x*lambdaf[i](radii[j])
        weight["Fe"][i][j] = y*lambdaf[i](radii[j])
        weight["Pb"][i][j] = z*lambdaf[i](radii[j])

print(weight["Al"])
print(weight["Fe"])
print(weight["Pb"])

[[  1.57079633   6.28318531  14.13716694]
 [  3.14159265  12.56637061  28.27433388]
 [  8.37758041  67.02064328 226.19467106]]
[[  9.42477796  37.69911184  84.82300165]
 [ 12.56637061  50.26548246 113.09733553]
 [ 20.94395102 167.55160819 565.48667765]]
[[  47.1238898   188.49555922  424.11500823]
 [  62.83185307  251.32741229  565.48667765]
 [ 125.66370614 1005.30964915 3392.92006588]]


6\. Edit the class defintion to add an instance attribute of is_hungry = True to the Dog class. Then add a method called eat() which changes the value of is_hungry to False when called. Figure out the best way to feed each dog and then output “My dogs are hungry.” if all are hungry or “My dogs are not hungry.” if all are not hungry. The final output should look like this:

`I have 3 dogs. 
Tom is 6. 
Fletcher is 7. 
Larry is 9. 
And they're all mammals, of course. 
My dogs are not hungry.
`

```python
# Parent class
class Dog:

    # Class attribute
    species = 'mammal'

    # Initializer / Instance attributes
    def __init__(self, name, age):
        self.name = name
        self.age = age

    # instance method
    def description(self):
        return "{} is {} years old".format(self.name, self.age)

    # instance method
    def speak(self, sound):
        return "{} says {}".format(self.name, sound)

# Child class (inherits from Dog class)
class RussellTerrier(Dog):
    def run(self, speed):
        return "{} runs {}".format(self.name, speed)

# Child class (inherits from Dog class)
class Bulldog(Dog):
    def run(self, speed):
        return "{} runs {}".format(self.name, speed)
```

In [92]:
# Parent class
class Dog:

    # Class attribute
    species = 'mammal'
    is_hungry = True

    # Initializer / Instance attributes
    def __init__(self, name, age):
        self.name = name
        self.age = age

    # instance method
    def description(self):
        return "{} is {} years old".format(self.name, self.age)

    # instance method
    def speak(self, sound):
        return "{} says {}".format(self.name, sound)
    
    def eat():
        is_hungry = False

# Child class (inherits from Dog class)
class RussellTerrier(Dog):
    def run(self, speed):
        return "{} runs {}".format(self.name, speed)

# Child class (inherits from Dog class)
class Bulldog(Dog):
    def run(self, speed):
        return "{} runs {}".format(self.name, speed)

dogList = []
Tom = Bulldog("Tom", 6)
dogList.append(Tom)
Fletcher = RussellTerrier("Fletcher", 7)
dogList.append(Fletcher)
Larry = Bulldog("Larry", 9)
dogList.append(Larry)

all_mammals = True
all_hungry = True
print("I have ", len(dogList), "dogs")
for i in dogList:
    print(i.description())
    all_mammals *= (i.species == 'mammal')
    all_hungry *= i.is_hungry

if all_mammals == True:
    print("And they're all mammals, of course")
else:
    print("They're not all mammals")

if all_hungry == True:
    print("My dogs are all hungry")
else:
    print("My dogs are not hungry")


I have  3 dogs
Tom is 6 years old
Fletcher is 7 years old
Larry is 9 years old
And they're all mammals, of course
My dogs are all hungry
